[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
